name: Release Stable
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[🚀 Release]')"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GIT_TOKEN }}
            - uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"
            - run: git config --global user.name 'Patryk Rzucidlo (@PTKDev)'
            - run: git config --global user.email 'support@ptkdev.io'
            - run: npm ci
            - run: npm run github-workflow-next-version -- --cmd main
            - run: npm run release
            - run: npm run pre-commit
            - id: pkgjson
              run: chmod +x ./scripts/version.sh && ./scripts/version.sh
            - run: git add . && git commit -m "[🚀 Release] v${{ steps.pkgjson.outputs.pkgversion }}" && git push
            - run: npm publish --tag latest
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%B %d, %Y')"
            - run: npm run github-workflow-changelog
            - id: changelog
              run: chmod +x ./scripts/changelog_release.sh && ./scripts/changelog_release.sh
            - name: Release snapshot
              id: release-snapshot
              uses: actions/create-release@latest
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.pkgjson.outputs.pkgversion }}
                  release_name: v${{ steps.pkgjson.outputs.pkgversion }}
                  body: |
                      ### CHANGELOG: v${{ steps.pkgjson.outputs.pkgversion }} (${{ steps.date.outputs.date }})${{ steps.changelog.outputs.changelog }}
                  draft: false
                  prerelease: false
