name: Try Release
on:
    push:
        branches:
            - nightly
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GIT_TOKEN }}
                  ref: nightly
            - uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"
            - run: git config --global user.name 'Patryk Rzucidlo (@PTKDev)'
            - run: git config --global user.email 'support@ptkdev.io'
            - run: npm ci
            - run: npm run release
